const fs = require('fs');
const path = require('path');

const jsFilePath = path.join(__dirname, 'html_js_dashboard/dashboard_data.js');
const jsonFilePath = path.join(__dirname, 'react_responsive_website/dashboard-backend/data/dashboard_data.json');

const content = fs.readFileSync(jsFilePath, 'utf8');

// The file starts with:
// // Auto-generated by generate_dashboard_data.py
// const DASHBOARD_DATA = {
// and export or ends. We need to extract the JSON object.

const startIndex = content.indexOf('{');
if (startIndex !== -1) {
  let jsonData = content.substring(startIndex);
  // Remove any trailing semicolons or whitespace
  jsonData = jsonData.trim();
  if (jsonData.endsWith(';')) {
    jsonData = jsonData.slice(0, -1);
  }
  
  // Validate JSON
  try {
    JSON.parse(jsonData);
    fs.writeFileSync(jsonFilePath, jsonData, 'utf8');
    console.log('Successfully extracted JSON to', jsonFilePath);
  } catch (e) {
    console.error('Failed to parse JSON:', e);
  }
} else {
  console.log('Could not find start of JSON');
}
