/**
 * Dashboard Logic
 * Handles Chart.js rendering and data injection
 */

// ── Chart.js Global Config ──────────────────────────────────────────────
Chart.defaults.color = '#94a3b8';
Chart.defaults.borderColor = '#e2e5ee';
Chart.defaults.font.family = "'Inter', sans-serif";
Chart.defaults.plugins.legend.labels.usePointStyle = true;
Chart.defaults.animation.duration = 700;

// The DASHBOARD_DATA object is loaded from dashboard_data.js automatically generated by Python.
// Doing it this way saves us from having to run a live web server or external API just for this HTML page.
const D = typeof DASHBOARD_DATA !== 'undefined' ? DASHBOARD_DATA : null;

if (!D) {
    document.querySelector('.main').innerHTML = `
        <div style="text-align:center;padding:80px 20px;">
            <h2 style="color:#1e293b;margin-bottom:12px;">⏳ Data Not Yet Generated</h2>
            <p style="color:#64748b;max-width:500px;margin:0 auto;line-height:1.7;">
                Run <code style="background:#f1f5f9;padding:2px 8px;border-radius:4px;">python3 generate_dashboard_data.py</code>
                to download and process the NYC TLC data.<br>The script generates <code>dashboard_data.js</code> which this dashboard reads automatically.
            </p>
        </div>`;
} else {
    document.addEventListener("DOMContentLoaded", renderAll);
}

function fmt(n) {
    if (n >= 1e9) return (n/1e9).toFixed(1)+'B';
    if (n >= 1e6) return (n/1e6).toFixed(1)+'M';
    if (n >= 1e3) return Math.round(n).toLocaleString();
    return String(n);
}

function renderAll() {
    const k = D.kpis;

    // KPIs
    document.getElementById('kpi-total').textContent = fmt(k.total_trips);
    document.getElementById('kpi-total-sub').textContent = k.date_range || '';
    document.getElementById('kpi-daily').textContent = fmt(k.avg_daily);
    document.getElementById('kpi-peak').textContent = `${String(k.peak_hour).padStart(2,'0')}:00`;
    document.getElementById('kpi-peak-sub').textContent = k.peak_hour >= 17 ? 'Evening rush' : k.peak_hour >= 7 ? 'Morning rush' : 'Night';
    document.getElementById('kpi-dist').textContent = k.avg_distance + ' mi';
    document.getElementById('kpi-fare').textContent = '$' + k.avg_fare;
    document.getElementById('kpi-zone').textContent = '#' + k.top_zone_id;
    document.getElementById('kpi-zone-sub').textContent = `${k.files_processed} files processed`;
    document.getElementById('date-range').textContent = k.date_range || 'Post-COVID';

    // Hourly
    const hCtx = document.getElementById('chart-hourly');
    const hGrad = hCtx.getContext('2d').createLinearGradient(0, 0, 0, 340);
    hGrad.addColorStop(0, 'rgba(79, 70, 229, 0.18)');
    hGrad.addColorStop(1, 'rgba(79, 70, 229, 0.0)');

    new Chart(hCtx, {
        type: 'line',
        data: {
            labels: D.hourly.map(h => `${String(h.hour).padStart(2,'0')}:00`),
            datasets: [{
                label: 'Avg Trips/Hour',
                data: D.hourly.map(h => h.avg),
                fill: true, backgroundColor: hGrad,
                borderColor: '#4f46e5', borderWidth: 2.5,
                pointRadius: 4, pointBackgroundColor: '#4f46e5',
                pointBorderColor: '#fff', pointBorderWidth: 2,
                pointHoverRadius: 7, tension: 0.4,
            }]
        },
        options: {
            responsive: true, maintainAspectRatio: false,
            plugins: { legend: { display: false },
                tooltip: { backgroundColor: '#1e293b', titleColor: '#fff', bodyColor: '#cbd5e1', padding: 12, cornerRadius: 8,
                    callbacks: { label: c => `${c.parsed.y.toLocaleString()} trips (avg)` } }
            },
            scales: {
                y: { beginAtZero: true, grid: { color: '#f1f5f9' }, ticks: { callback: v => fmt(v) } },
                x: { grid: { display: false } }
            }
        }
    });

    // Monthly
    new Chart(document.getElementById('chart-monthly'), {
        type: 'bar',
        data: {
            labels: D.monthly.map(m => m.label),
            datasets: [{
                label: 'Trips',
                data: D.monthly.map(m => m.trips),
                backgroundColor: D.monthly.map((_, i) => `hsl(${240 + i * 3}, 70%, ${55 + (i % 3) * 8}%)`),
                borderRadius: 6, borderSkipped: false,
            }]
        },
        options: {
            responsive: true, maintainAspectRatio: false,
            plugins: { legend: { display: false },
                tooltip: { backgroundColor: '#1e293b',
                    callbacks: { label: c => `${fmt(c.parsed.y)} trips` } }
            },
            scales: {
                y: { beginAtZero: true, grid: { color: '#f1f5f9' }, ticks: { callback: v => fmt(v) } },
                x: { grid: { display: false }, ticks: { maxRotation: 60, font: { size: 10 } } }
            }
        }
    });

    // Zones
    const top10 = D.zones.slice(0, 10);
    new Chart(document.getElementById('chart-zones'), {
        type: 'bar',
        data: {
            labels: top10.map(z => `#${z.id}`),
            datasets: [{
                label: 'Trips',
                data: top10.map(z => z.trips),
                backgroundColor: ['#4f46e5','#6366f1','#818cf8','#059669','#34d399',
                                   '#d97706','#fbbf24','#0284c7','#e11d48','#7c3aed'],
                borderRadius: 5, borderSkipped: false,
            }]
        },
        options: {
            indexAxis: 'y',
            responsive: true, maintainAspectRatio: false,
            plugins: { legend: { display: false },
                tooltip: { backgroundColor: '#1e293b',
                    callbacks: { label: c => `${fmt(c.parsed.x)} trips` } }
            },
            scales: {
                x: { beginAtZero: true, grid: { color: '#f1f5f9' }, ticks: { callback: v => fmt(v) } },
                y: { grid: { display: false } }
            }
        }
    });

    // Weekly
    new Chart(document.getElementById('chart-weekly'), {
        type: 'bar',
        data: {
            labels: D.weekly.map(w => w.day),
            datasets: [{
                label: 'Avg Weekly Trips',
                data: D.weekly.map(w => w.avg),
                backgroundColor: ['#e11d48','#d97706','#059669','#0284c7','#4f46e5','#7c3aed','#db2777'],
                borderRadius: 8, borderSkipped: false,
            }]
        },
        options: {
            responsive: true, maintainAspectRatio: false,
            plugins: { legend: { display: false },
                tooltip: { backgroundColor: '#1e293b',
                    callbacks: { label: c => `${fmt(c.parsed.y)} trips (avg)` } }
            },
            scales: {
                y: { beginAtZero: true, grid: { color: '#f1f5f9' }, ticks: { callback: v => fmt(v) } },
                x: { grid: { display: false } }
            }
        }
    });

    // Revenue
    const rCtx = document.getElementById('chart-revenue');
    const rGrad = rCtx.getContext('2d').createLinearGradient(0, 0, 0, 280);
    rGrad.addColorStop(0, 'rgba(5, 150, 105, 0.15)');
    rGrad.addColorStop(1, 'rgba(5, 150, 105, 0.0)');

    new Chart(rCtx, {
        type: 'line',
        data: {
            labels: D.monthly.map(m => m.label),
            datasets: [{
                label: 'Revenue',
                data: D.monthly.map(m => m.revenue),
                fill: true, backgroundColor: rGrad,
                borderColor: '#059669', borderWidth: 2.5,
                pointRadius: 4, pointBackgroundColor: '#059669',
                pointBorderColor: '#fff', pointBorderWidth: 2,
                tension: 0.4,
            }]
        },
        options: {
            responsive: true, maintainAspectRatio: false,
            plugins: { legend: { display: false },
                tooltip: { backgroundColor: '#1e293b',
                    callbacks: { label: c => `$${fmt(c.parsed.y)}` } }
            },
            scales: {
                y: { beginAtZero: false, grid: { color: '#f1f5f9' }, ticks: { callback: v => '$'+fmt(v) } },
                x: { grid: { display: false }, ticks: { maxRotation: 60, font: { size: 10 } } }
            }
        }
    });

    // Daily
    const rolling = [];
    for (let i = 0; i < D.daily.length; i++) {
        if (i < 6) { rolling.push(null); continue; }
        let sum = 0;
        for (let j = i - 6; j <= i; j++) sum += D.daily[j].trips;
        rolling.push(Math.round(sum / 7));
    }

    new Chart(document.getElementById('chart-daily'), {
        type: 'line',
        data: {
            labels: D.daily.map(d => d.date),
            datasets: [
                {
                    label: 'Daily Trips',
                    data: D.daily.map(d => d.trips),
                    borderColor: 'rgba(79, 70, 229, 0.25)', borderWidth: 1,
                    pointRadius: 0, fill: false,
                },
                {
                    label: '7-Day Rolling Avg',
                    data: rolling,
                    borderColor: '#e11d48', borderWidth: 2.5,
                    pointRadius: 0, fill: false,
                }
            ]
        },
        options: {
            responsive: true, maintainAspectRatio: false,
            interaction: { mode: 'index', intersect: false },
            plugins: { legend: { position: 'top' },
                tooltip: { backgroundColor: '#1e293b',
                    callbacks: { label: c => `${c.dataset.label}: ${c.parsed.y?.toLocaleString() ?? '—'} trips` } }
            },
            scales: {
                y: { beginAtZero: false, grid: { color: '#f1f5f9' }, ticks: { callback: v => fmt(v) } },
                x: { grid: { display: false }, ticks: { maxTicksLimit: 15, callback: function(v) { return this.getLabelForValue(v)?.slice(5) || ''; } } }
            }
        }
    });

    // Stats Table
    const stb = document.getElementById('stats-tbody');
    stb.innerHTML = D.stats.map(s => {
        const fitClass = `fit-${s.best_fit_dist || 'unknown'}`;
        return `<tr>
            <td><strong>${s.feature}</strong></td>
            <td>${s.mean}</td><td>${s.median}</td><td>${s.std}</td>
            <td>${s.skewness}</td><td>${s.kurtosis}</td>
            <td><span class="fit-badge ${fitClass}">${s.best_fit_dist || '—'}</span></td>
            <td>${s.ks_pvalue}</td>
        </tr>`;
    }).join('');

    // Zones Table
    const ztb = document.getElementById('zones-tbody');
    ztb.innerHTML = D.zones.slice(0, 20).map((z, i) => `
        <tr>
            <td><span class="zone-rank">${i+1}</span></td>
            <td><strong>#${z.id}</strong></td>
            <td>${Number(z.trips).toLocaleString()}</td>
            <td>${z.avg_dist} mi</td>
            <td>$${z.avg_fare}</td>
            <td>$${Number(z.revenue).toLocaleString()}</td>
        </tr>
    `).join('');
}
